### ISSUE TITLE
How about simple componentization such as core log start queue timing tasks...Composer? https://www.yiiframework.com/status/3.0

### ISSUE THREAD

**Issue by zhanchmini** [suvera/winter-boot#3]
How about simple componentization such as core log start queue timing tasks...Composer?https://www.yiiframework.com/status/3.0

I wanted to return Swoole with Workerman and found it too coupling

**Comment by zhanchmini** [comment]
Or just do the injection startup and so on and leave it to another framework?

**Comment by suvera** [comment]
@zhanchmini 

few basic points just want to re-iterate

- My intention is to make WinterBoot Framework as a stateful  framework.  It maintains it's state between requests. 
- This is mainly designed for backend processing, rather frontend. 
- NO on-demand Process created per Request  (unlike normal PHP frameworks)


----

1) Most of the YII components work just by including them by Composer in your project.  i.e. Components which are stateless such as Arrays, ActiveRecord etc ...

2) Some Components has to be started on Application startup, such as Logging, Schedulers etc...

    - Schedulers can be used with a Annotation **#[Scheduled]**.  see https://github.com/suvera/winter-boot/blob/master/docs/async_scheduling.md
    - WinterBoot already use  Monolog,  incase if you want to do something else, then use **#[OnApplicationReady]**
```php
      #[Component]
      #[OnApplicationReady]
      class SomthingOnReady implements ApplicationReadyEvent {
      }
```


- YII Components such as Queue listeners, processors  can be started by **#[DaemonThread]**. See Help here https://github.com/suvera/winter-boot/blob/master/docs/daemon_threads.md
- Other Complex Things has to be created as a Module  , see **Module Extensions** section here https://github.com/suvera/winter-boot/blob/master/README.md
